## First Stage
FROM node:lts-alpine3.20 as build

WORKDIR /build

COPY package*.json ./

RUN ["npm","install"]

COPY ./ ./

RUN ["npx","prisma","generate"]

RUN ["npm","run","build"]


## Second Stage
FROM node:lts-alpine3.20 as production

WORKDIR /prod

## arg variables

ARG FIREBASE_APIKEY_ARG=
ARG FIRBASE_AUTHDOMAIN_ARG=
ARG FIREBASE_PROJECT_ID_ARG=
ARG FIREBASE_STORAGE_BUCKET_ARG=
ARG FIREBASE_MESSAGING_SENDER_ID_ARG=
ARG FIREBASE_APP_ID_ARG=
ARG FIREBASE_MEASUREMENT_ID_ARG=
ARG NODE_ENV_ARG="development"
ARG DATABASE_URL_ARG=
ARG JWT_SECRET_ARG=
ARG GOOGLE_CLIENT_ID_ARG=
ARG GOOGLE_CLIENT_SECRET_ARG=
ARG GITHUB_CLIENT_ID_ARG=
ARG GITHUB_CLIENT_SECRET_ARG=
ARG SMTP_HOST_ARG=
ARG SMTP_PORT_ARG=
ARG SMTP_USER_ARG=
ARG SMTP_PASSWORD_ARG=
ARG TWILIO_ACCOUNT_SID_ARG=
ARG TWILIO_AUTH_TOKEN_ARG=
ARG INFOBIP_API_KEY_ARG=
ARG BACKEND_URL_ARG=
ARG FRONTEND_URL_ARG=

## env variables
ENV FIREBASE_APIKEY=${FIREBASE_APIKEY_ARG}
ENV FIRBASE_AUTHDOMAIN=${FIRBASE_AUTHDOMAIN_ARG}
ENV FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID_ARG}
ENV FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET_ARG}
ENV FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID_ARG}
ENV FIREBASE_APP_ID=${FIREBASE_APP_ID_ARG}
ENV FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID_ARG}
ENV NODE_ENV=${NODE_ENV_ARG}
ENV DATABASE_URL=${DATABASE_URL_ARG}
ENV JWT_SECRET=${JWT_SECRET_ARG}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_ARG}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
ENV GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET_ARG}
ENV SMTP_HOST=${SMTP_HOST_ARG}
ENV SMTP_PORT=${SMTP_PORT_ARG}
ENV SMTP_USER=${SMTP_USER_ARG}
ENV SMTP_PASSWORD=${SMTP_PASSWORD_ARG}
ENV TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID_ARG}
ENV TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN_ARG}
ENV INFOBIP_API_KEY=${INFOBIP_API_KEY_ARG}
ENV BACKEND_URL=${BACKEND_URL_ARG}
ENV FRONTEND_URL=${FRONTEND_URL_ARG}
ENV REDIS_HOST=
ENV REDIS_PORT=
ENV REDIS_PASSWORD=

## Copying

COPY --from=build /build/build ./build

COPY --from=build /build/node_modules ./node_modules

COPY --from=build /build/package*.json ./

COPY --from=build /build/prisma ./prisma

COPY ./serviceAccountKey.json ./serviceAccountKey.json

EXPOSE 3000

CMD ["npm","run","container"]
