"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var groupRoutes_1 = require("./groupRoutes");
var adminRoutes_1 = require("./adminRoutes");
var authRoutes_1 = require("./authRoutes");
var channelRoutes_1 = require("./channelRoutes");
var profileRoutes_1 = require("./profileRoutes");
var storiesRoutes_1 = require("./storiesRoutes");
var searchRoutes_1 = require("./searchRoutes");
var userRoutes_1 = require("./userRoutes");
var chatRoutes_1 = require("./chatRoutes");
var authMiddleware_1 = require("../middlewares/authMiddleware");
var router = express_1.default.Router();
router.use('/v1/auth', authRoutes_1.default);
router.use(authMiddleware_1.isAuthenticated);
router.use('/v1/admins', adminRoutes_1.default);
router.use('/v1/groups', groupRoutes_1.default);
router.use('/v1/channels', channelRoutes_1.default);
router.use('/v1/profile', profileRoutes_1.default);
router.use('/v1/stories', storiesRoutes_1.default);
router.use('/v1/search', searchRoutes_1.default);
router.use('/v1/user', userRoutes_1.default);
router.use('/v1/chats', chatRoutes_1.default);
exports.default = router;
