name: push workflow

on:
  workflow_run:
    workflows: ["main workflow"]
    types:
      - success

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.head_branch == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: login to registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build image
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/back-app:${{ github.run_number }} .
      - name: push image
        run: docker push ${{vars.DOCKERHUB_USERNAME}}/back-app:${GITHUB_RUN_NUMBER}
        
