name: push workflow

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: login to registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/back-app:${{ github.run_number }} .
      - name: push image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/back-app:${{ github.run_number }}
        
