name: push workflow

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: login to registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Write Secret Account Key
        run: |
         echo $SERVICE_ACCOUNT_KEY >> ./serviceAccountKey.json
        shell: bash
        env:
          SERVICE_ACCOUNT_KEY : ${{secrets.SERVICE_ACCOUNT_KEY}}
      - name: build image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/back-app:${{ github.run_number }} .
      - name: tag image
        run: docker tag ${{ vars.DOCKER_USERNAME }}/back-app:${{ github.run_number }} ${{ vars.DOCKER_USERNAME }}/back-app:latest
      - name: push image-tag
        run: docker push ${{ vars.DOCKER_USERNAME }}/back-app:${{ github.run_number }}
      - name: push image-latest
        run: docker push ${{ vars.DOCKER_USERNAME }}/back-app:latest
        
