name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Automatically use the latest LTS version

      - name: Install dependencies
        run: npm install

      - name: TypeScript Compilation Check
        run: npx tsc --noEmit
        env:
          CI: true

